package io.ara.core.agent;

import io.ara.core.common.AgentId;

import java.util.List;
import java.util.Objects;
import java.util.concurrent.Executor;
import java.util.function.Function;

/**
 * Static convenience helpers built on top of the minimal {@link AraAgent} contract.
 *
 * <p>Kept separate from the interface so {@code AraAgent} stays a small set of
 * methods every implementation must reason about; these are derived operations
 * with no per-implementation state.
 */
public final class AraAgents {

    private AraAgents() {}

    /** Submits a plain-text prompt and returns the full {@link AgentResponse}. */
    public static AgentResponse ask(AraAgent agent, String prompt) {
        Objects.requireNonNull(agent, "agent must not be null");
        return agent.execute(AgentTask.of(prompt));
    }

    /**
     * Submits a plain-text prompt and returns only the answer text — the empty string when
     * the execution failed, since {@link AgentResponse#failure} sets {@code content} to
     * {@code ""}. No null check is needed: {@code AgentResponse} rejects a null
     * {@code content} in its compact constructor, so {@code content()} is never null.
     */
    public static String askText(AraAgent agent, String prompt) {
        return ask(agent, prompt).content();
    }

    /**
     * Asynchronous execution on virtual threads.
     *
     * @param executor typically {@code AraRuntime.executor()}
     */
    public static AgentFuture executeAsync(AraAgent agent, AgentTask task, Executor executor) {
        Objects.requireNonNull(agent, "agent must not be null");
        Objects.requireNonNull(task, "task must not be null");
        return AgentFuture.async(() -> agent.execute(task), executor);
    }

    /**
     * Builds a deterministic agent: an {@link AraAgent} whose answer is computed by
     * {@code body} rather than generated by a model.
     *
     * <p>The door for work that has no business reasoning — a renderer, a normaliser, a
     * validator, a rule-based classifier, an adapter over an existing service. There is
     * nowhere in this signature to put an {@code LlmClient}, which is the point: the
     * absence of reasoning is a property of the type, not a flag to be checked, and the
     * alternative it replaces is hosting the work in a full agent handed a stub
     * {@code LlmClient} that throws if anything ever calls it.
     *
     * <p>Read {@link FunctionAgent}'s javadoc before reaching for this in place of a
     * configured agent: the result reports zero usage rather than absent usage, and it
     * carries none of {@code AgentInstance}'s capabilities (per-session isolation, busy
     * policy, cancellation, telemetry span, interceptors).
     *
     * <pre>{@code
     * AraAgent renderer = AraAgents.deterministic(AgentId.of("renderer"),
     *         task -> engine.render(template, task.input()));
     * }</pre>
     *
     * @param agentId this agent's identity
     * @param body    the work; a {@code null} return or a thrown {@link RuntimeException}
     *                becomes a failed {@link AgentResponse}, never a propagated throw
     */
    public static AraAgent deterministic(AgentId agentId, Function<AgentTask, String> body) {
        return deterministic(agentId, FunctionAgent.defaultConfig(agentId), body);
    }

    /**
     * Like {@link #deterministic(AgentId, Function)}, but with a caller-supplied {@link
     * AgentConfig} instead of {@link FunctionAgent#defaultConfig(AgentId)} — for an agent
     * that needs its own {@code agentType()}, {@code name()}, {@code description()} or
     * {@code tags()}, all of which surface through {@link #agentCard(AraAgent)}.
     */
    public static AraAgent deterministic(AgentId agentId, AgentConfig config, Function<AgentTask, String> body) {
        return new FunctionAgent(agentId, config, FunctionAgent.respondingWith(agentId, body));
    }

    /**
     * Returns a machine-readable description of the agent's identity and capabilities,
     * derived from its current {@link AgentConfig}.
     */
    public static AgentCard agentCard(AraAgent agent) {
        Objects.requireNonNull(agent, "agent must not be null");
        AgentConfig config = agent.config();
        AgentIdentity id = config.identity();
        AgentCapabilities caps = new AgentCapabilities(
                config.streamingEnabled(),
                config.maxConversationTurns() > 0,
                List.of(config.plannerStrategy()));
        return new AgentCard(id.agentId(), id.name(), id.description(), id.version(), caps,
                config.requiredScopes(), List.of("none"));
    }
}
