package io.ara.core.tool;

/**
 * Where a tool came from (ADR-0067 D1 / ADR-0063). A {@link #SYNTHESIZED} tool carries
 * extra construction-time obligations on its {@link ToolSpec} — a sandbox policy and at
 * least one test (§3.2.6, non-negotiable).
 */
public enum ToolOrigin {
    /** Hand-written, shipped with ARA or the application (e.g. {@code ara-tools}). */
    BUILTIN,
    /** Generated by the evolutionary meta-agent (ADR-0084). */
    SYNTHESIZED
}
